//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Not_Bankası.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UyeBilgileri()
        {
            this.YorumBilgileris = new HashSet<YorumBilgileri>();
        }
    
        public int Uye_Id { get; set; }
        public string İsim { get; set; }
        public string Soyisim { get; set; }
        public string Resim { get; set; }
        public string EMail { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> Universite_Id { get; set; }
        public Nullable<int> Bolum_Id { get; set; }
        public Nullable<int> Yorum_Id { get; set; }
        public Nullable<int> Not_Id { get; set; }
    
        public virtual NotBilgileri NotBilgileri { get; set; }
        public virtual Universite Universite { get; set; }
        public virtual Universite_Bolum Universite_Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YorumBilgileri> YorumBilgileris { get; set; }
    }
}
